version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=d53lhf1gsje7j9
      - POSTGRES_USER=tcrtuckndccarx
      - POSTGRES_PASSWORD=3102db78685e796440ae3e52671069230842c5bdf60d884ef6d37681b37fe529
  tortk:
    build: .
    command: bash start.sh
    ports:
      - "80:80"
    depends_on: 
      - db
