version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=dcrhcj57dchqmr
      - POSTGRES_USER=bxpipvspprnhcd
      - POSTGRES_PASSWORD=ae4b37042a86e29bf4fec196a3e805bde234b4abe94eeabc7c85c039d5368bca
  tortk:
    build: .
    command: bash start.sh
    ports:
      - "80:80"
    depends_on: 
      - db
