version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=d32vubrgat3s8m
      - POSTGRES_USER=yhyncntovmzndv
      - POSTGRES_PASSWORD=2f25289efc5e3788a7be7c45e5edc8eca74735248bc996920d72ea67e684f391
  tortk:
    build: .
    command: bash start.sh
    ports:
      - "80:80"
    depends_on: 
      - db
